### ISSUE TITLE
How do we make sure the lawn stays mowed?

### ISSUE THREAD

**Issue by imlucas** [mongodb-js/mongodb-js.github.io#17]
We need an operating model to make sure this org doesn't become a graveyard.  Some questions that have come up:
- If tests are failing on a project's default branch, who is going to make sure it gets back to green quickly?
- Who makes sure pull requests are handled? 
- Who makes sure issues created by users are considered and responded to?
- What checks can we put in place to make sure this all happens?
- Who settles disputes for combining/splitting modules?

I'm inclined to adapt [iojs/GOVERNANCE.md](https://github.com/iojs/io.js/blob/v1.x/GOVERNANCE.md) to our needs.  Adding a @mongodb-js/tc team would assign people to all of the above.  Regularly scheduled (bi-weekly? monthly?) @mongodb-js/tc google hangouts would provide transparency and a way to make sure we're not slipping.  @mongodb-js/tc would require just a few hours a week per member, but we're not blocked for 12 days because 1 team is really busy.

Thoughts?

**Comment by rueckstiess** [comment]
A lot of iojs' model is probably overkill for us at the moment. But regular hangouts and some lightweight process sound like a good idea. Since we're geographically distributed we should try to handle a lot of these async, e.g. use github issues, tags, ...

**Comment by vkarpov15** [comment]
+1 @rueckstiess, I don't foresee having as many heavily-invested outside contributors for any one module as io.js, at least in the near future. Makes sense if we start seeing one module getting slammed with issues and PRs. However, the idea of a weekly hangout / meeting is important IMO - when you don't have regular touch points you have no idea what other people are working on. I'd like to see us have a regular meeting if for nothing but to share ideas and make sure we don't have two people doing the same work.

**Comment by christkv** [comment]
+1 @rueckstiess once a week or every two weeks would be awesome.
