### ISSUE TITLE
tooling to help transfer repos to the org

### ISSUE THREAD

**Issue by imlucas** [mongodb-js/mongodb-js.github.io#2]
Can't do this by hand, so let's write some tooling to help.
- [ ] update badges in README
- [ ] update repo/url in package.json && git commit -a -m "Moving into mongodb-js org" && npm version patch && git push --tags && npm publish;
- [ ] find and replace <username> -> mongodb-js in .git/config 
- [ ] github api -> transfer repo to org
- [ ] update travis GH app to allow mongodb-js (fails silently)
- [ ] travis resync

**Comment by rueckstiess** [comment]
made an empty shell + some docopt at https://github.com/rueckstiess/mj

**Comment by imlucas** [comment]
Broke off as rueckstiess/mj#1
