### ISSUE TITLE
Open questions for mongodb-js org

### ISSUE THREAD

**Issue by rueckstiess** [mongodb-js/mongodb-js.github.io#5]
Let's discuss some open questions and ideas in this issue with the goal to create a guide for new contributions and migrations from existing private repos into mongodb-js.
### I. All repos/projects under mongodb-js
1. What are the requirements for any repo inside mongodb-js? 
   - a) Documentation
   - b) Tests
   - c) Code Coverage
   - d) Code Style / Conventions
   - e) npm (does every repo under mongodb-js need to be hosted on npm?)
2. Does it make sense to classify projects into different types? And how is the type stored and enforced? E.g. 
   - CLI (a command line tool installable with npm)
   - SPA (single-page application running entirely on client)
   - Full Client/Server app
   - Utility (small helper functions and code snippets)
   - Non-App (specs, docs, guidelines, ...)
3. `mj` - a CLI app that helps manage and orchestrate mongodb-js
   - a) What features does it need?
   - b) Who writes it?
4. How do we handle combining/deduping functionality? 
### II. Migrating existing projects
1. What steps are required?
2. What can we automate? 
3. How do we handle currently private projects?
4. How do we enforce requirements (see I.1)
### III. Creating new projects under mongodb-js
1. How to create "hello world" scaffold app? --> use `mj create`
2. Have you ticked all the requirements boxes? --> use `mj check`
3. How to add to mongodb-js? --> use `mj add`

**Comment by rueckstiess** [comment]
**II.1.+2.  Automating migration**

Lucas already listed some required steps for automating the migrations in #2.  This should become part of `mj`.

Goal: Have a very simple process for next skunkworks, something like 

```
npm install -g mj
mj check .  
mj add .
```

**Comment by rueckstiess** [comment]
**I.1.c Code Coverage**

Lucas suggests: 
- [istanbul](https://gotwarlost.github.io/istanbul/) + [coveralls](https://coveralls.io/)
- example: [mongodb-js/log](https://coveralls.io/r/mongodb-js/log)

**Comment by rueckstiess** [comment]
**I.1.a Documentation**

A lot of different needs here. For general small modules, which of these options do we want?
- full blown jsdoc
- examples in README + comments where it makes sense
- `dox --api`
- Publish generated docs to github pages or fine just in README.md?

**Comment by rueckstiess** [comment]
**I.1.b Testing**
- every repo wired to travisci
- [zuul](https://github.com/defunctzombie/zuul) + [saucelabs](https://saucelabs.com/) for browser and ui projects
- server only modules: use [mongodb-js/version-manager](https://github.com/mongodb-js/version-manager) for great good!
- Can then add checks for:
  - using `MONGODB_VERSION` in .travis.yml?
  - Is this actaully tested against a MongoDB releases?
  - Is `MONGODB_VERSION` the latest stable release?

**Comment by rueckstiess** [comment]
**I.1.d. Code Style Guide**
- share Lucas' `.jsfmtrc` and `.jshintrc` configs + explain how to use/install
- as guideline (but hard to always enforce): [Google Javascript Style Guide](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml)

**Comment by imlucas** [comment]
Thanks!  Broken down into #7, #8, #9 for process and rueckstiess/mj#1, rueckstiess/mj#2, rueckstiess/mj#3 and rueckstiess/mj#4 for tooling.
