### ISSUE TITLE
docs/setup.md

### ISSUE THREAD

**Issue by imlucas** [mongodb-js/mongodb-js.github.io#6]
Should cover:
- [ ] how to install node.js/io.js on osx/linux/windows
- [ ] how to install and configure tooling (mj)

**Comment by rueckstiess** [comment]
@imlucas I'm just writing a `welcome.md` file for contributors to mongodb-js. Should I just put a setup section in there?

**Comment by imlucas** [comment]
@rueckstiess Ah yes good call!  Closing this one as dupe.
